# number_input = input("Pls enter series of numbers with coma: ")
# array = list(number_input)

# def bubble_sort(array):
#     n = len(array)

#     for i in range(n):        
#         already_sorted = True
         
#         for j in range(n - i - 1):
#             if array[j] > array[j + 1]:

#                 array[j], array[j + 1] = array[j + 1], array[j]

#                 already_sorted = False

#         if already_sorted:
#             break
#     return array




# import csv

# with open('coors.csv', mode='r') as infile:
#     reader = csv.reader(infile)
#     with open('coors_new.csv', mode='w') as outfile:
#         writer = csv.writer(outfile)
#         mydict = {rows[0]:rows[1] for rows in reader}

# import requests


# response = requests.get("http://api.openweathermap.org/data/2.5/forecast?id=7871736&APPID=336b102582e7d317c464efd5e6ac86aa")
# print(response.text)

# from datetime import datetime
# import winsound

# def davinchy_code():
#     result = datetime.datetime.now()
#     print(result)

# davinchy_code


# def davinchy_sum():
#     x = 23
#     y = 10
#     ans = (x + y)
#     print(f"The addition of {x} and {y} = {ans}")

# davinchy_sum()

# def greet(name, salutation):
#     print(f'{name},{salutation} how are you today')

# greet('lolu')

# def f(qty, item, price):
#     print(f'{qty} {item} cost ${price:.2f}')

# f('bananas', 6, 1.74)


# def h(my_list=[]):
#     my_list.append('###')
#     print(my_list)
#     return my_list

# h(['foo', 'mr', 'mrs'])

# def f(my_list=[]):
#     print(id(my_list))
#     my_list.append('###')
#     return my_list

# f()


# def h(my_list=[]):
#     my_list.append('###')
#     print(my_list)
#     return my_list

# h()
# h()
# h()
# h()









